version: "3.7"

services:
  ionos_ddns_updater:
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      Domains_0: "*.test.de;Key"
      Domains_1: "*.test.de;Key"
