version: "3.7"

services:
  ionos_ddns_updater:
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      LogLevel: "Debug"
      DOMAIN-0: "sub.domain.de;key"
      DOMAIN-1: "sub.domain.de;key"
