version: "3.7"

services:
  ionos_ddns_updater:
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      API_Key: ""
      DOMAINS: "subdomain.domain.de,domain.de"
